# Generated by Django 4.1.3 on 2022-12-27 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('completed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('sender', models.CharField(blank='True', max_length=100)),
                ('receiver', models.CharField(blank='True', default='N/A', max_length=100)),
                ('time_shipment', models.DateTimeField(blank=True, null=True)),
                ('supply_chain', models.CharField(blank='True', max_length=100)),
                ('issue', models.BooleanField(default=False)),
                ('hash', models.CharField(default='0a51c6e785b211ed8169b025aa349790', max_length=1000)),
                ('previous_hash', models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(blank='True', max_length=100)),
                ('disease', models.CharField(max_length=200)),
                ('dosage', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SupplyChain',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('origin', models.CharField(max_length=100)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scm.cart')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank='True', max_length=100)),
                ('id_user', models.IntegerField()),
                ('role', models.CharField(max_length=100)),
                ('profileimg', models.ImageField(default='blank-profile-picture.png', upload_to='profile_images')),
                ('status', models.CharField(default='Inactive', max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartItems',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('vaccine_name', models.CharField(blank='True', max_length=100)),
                ('vaccine_quantity', models.IntegerField()),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartitems', to='scm.cart')),
            ],
        ),
    ]
