# Generated by Django 4.1.3 on 2022-12-27 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scm', '0003_supplychain_ownership_alter_shipment_hash_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplychain',
            old_name='item',
            new_name='cart',
        ),
        migrations.AlterField(
            model_name='shipment',
            name='hash',
            field=models.CharField(default='93e40e4185b411ed9b7bb025aa349790', max_length=1000),
        ),
    ]
