# Generated by Django 4.1.3 on 2022-12-27 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scm', '0005_alter_shipment_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='hash',
            field=models.CharField(default='c3f7123685b411ed9e74b025aa349790', max_length=1000),
        ),
        migrations.AlterField(
            model_name='supplychain',
            name='ownership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scm.profile'),
        ),
    ]
