# Generated by Django 4.1.3 on 2022-12-27 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scm', '0006_alter_shipment_hash_alter_supplychain_ownership'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplychain',
            name='status_transferring',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='hash',
            field=models.CharField(default='96ca41d885b711ed91e1b025aa349790', max_length=1000),
        ),
    ]
