# Generated by Django 4.1.3 on 2022-12-27 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scm', '0007_supplychain_status_transferring_alter_shipment_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='issue',
        ),
        migrations.AddField(
            model_name='shipment',
            name='status',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='hash',
            field=models.CharField(default='7ab8717585c111ed9840b025aa349790', max_length=1000),
        ),
    ]
