# Generated by Django 4.1.3 on 2022-12-27 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scm', '0008_remove_shipment_issue_shipment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplychain',
            name='issue',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='hash',
            field=models.CharField(default='9d234b6085dc11edb8f4b025aa349790', max_length=1000),
        ),
    ]
