# Generated by Django 4.1.3 on 2022-12-28 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scm', '0009_supplychain_issue_alter_shipment_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.CharField(blank='True', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='password',
            field=models.CharField(blank='True', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(blank='True', max_length=100),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='hash',
            field=models.CharField(default='c003ec6e869011ed95cab025aa349790', max_length=1000),
        ),
    ]
