# Generated by Django 4.1.4 on 2022-12-31 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scm', '0012_alter_shipment_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='hash',
            field=models.CharField(default='c9222b1988de11ed898db025aa349790', max_length=1000),
        ),
        migrations.AlterField(
            model_name='supplychain',
            name='time_created',
            field=models.DateTimeField(),
        ),
    ]
