# Generated by Django 4.1.4 on 2023-01-03 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scm', '0014_alter_shipment_hash_alter_supplychain_time_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cartitems', to='scm.cart'),
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='vaccine_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='hash',
            field=models.CharField(default='7c7a497f8b2e11edba1fb025aa349790', max_length=1000),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='receiver',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='sender',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
