# Generated by Django 4.1.4 on 2023-01-03 16:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scm', '0015_alter_cartitems_cart_alter_cartitems_vaccine_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='hash',
            field=models.CharField(default='c80da4b88b4111ed89c9b025aa349790', max_length=1000),
        ),
        migrations.AlterField(
            model_name='supplychain',
            name='time_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
